M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu20.04.1} date sam. 02 déc. 2023 16:13:19
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-02T16:13:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X3.5117Y-1.7016
X3.5117Y-1.8984
T0
M30
